src/services/course_module/urls.py
from django.urls import path
from . import views
from .views import get_course_meta_data

app_name = "course_module"

urlpatterns = [
    path(
        "create_an_activity",
        views.create_an_activity,
        name="create_an_activity",
    ),
    path("save_an_activity", views.save_an_activity, name="save_an_activity"),
    path("define_a_course", views.define_a_course, name="define_a_course"),
    path(
        "save_course_meta_data",
        views.save_course_meta_data,
        name="save_course_meta_data",
    ),
    path(
        "define_course_activities_content",
        views.define_course_activities_content,
        name="define_course_activities_content",
    ),
    path(
        "get_course_meta_data",
        views.get_course_meta_data,
        name="get_course_meta_data",
    ),
    path(
        "get_course_activity_has_group",
        views.get_course_activity_has_group,
        name="get_course_activity_has_group",
    ),
]

src/services/services/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("ga_module/", include("ga_module.urls")),
    path("course_module/", include("course_module.urls")),
    path("user_module/", include("user_module.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/services/course_module/models.py
from django.db import models


# Create your models here.
class CourseActivity(models.Model):
    activity_name = models.CharField(max_length=100)
    has_groups = models.BooleanField()

    # class Meta:
    #     db_table = "course_activities"
    #     app_label = "course_module"
    #     app_name = "course_module"
    #     managed = False
    #     db_alias = "sample_db"

src/services/course_module/views.py
from django.shortcuts import render
from django.shortcuts import render
from .models import CourseActivity
from django import forms
from databases.database_connection import DatabaseConnection
from rest_framework.decorators import api_view
from rest_framework.response import Response
import json
from bson import json_util

mongo_db_connection = DatabaseConnection.create_database_connection("MongoDB")

mongo_db = mongo_db_connection.connect_to_mongo_database()
mongo_course_activity_collection = mongo_db["course_activities"]
mongo_course_meta_data = mongo_db["course_meta_data"]


class CreateNewActivity(forms.Form):
    activity = forms.CharField(label="New Activity", max_length=100)
    has_groups = forms.BooleanField(label="Has Groups", required=False)


def create_an_activity(request):
    return render(request, "course_module/create_an_activity.html")


def define_a_course(request):
    # Get data from mongo db about the all course activities
    course_activities = mongo_course_activity_collection.find({})

    return render(
        request,
        "course_module/define_a_course.html",
        {"course_activities": course_activities},
    )


def define_course_activities_content(request):
    # Get data from course_meta_data collcetion, first course code dynamically taken
    course_meta_data = mongo_course_meta_data.find({})
    # Match course_activity with -> course_activity collections's activity_name

    return render(
        request,
        "course_module/define_course_activities_content.html",
        {"course_activities": course_meta_data},
    )


@api_view(["POST"])
def get_course_meta_data(request):
    course_code = request.data

    course_meta_data = mongo_course_meta_data.find({"course_code": course_code})

    serialized_data = json.loads(json_util.dumps(course_meta_data))
    course_activities = [data["course_activities"] for data in serialized_data]

    print("Course activities : ", course_activities)
    return Response(course_activities[0])


@api_view(["POST"])
def get_course_activity_has_group(request):
    activity = request.data

    has_groups = mongo_course_activity_collection.find({"activity_name": activity})

    print("Has groups : ", has_groups)
    serialized_data = json.loads(json_util.dumps(has_groups))
    has_groups = serialized_data[0].get("has_groups")

    print(f" Activity {serialized_data[0]} Has groups : {has_groups}")
    return Response(has_groups)


def save_course_meta_data(request):

    if request.method == "POST":
        course_code = request.POST.get("courseCode")
        course_activities = request.POST.getlist("activities")

        print("Course code : ", course_code)
        print("Course has : ", course_activities)

        mongo_course_meta_data = mongo_db["course_meta_data"]

        course_meta_data = {
            "course_code": course_code,
            "course_activities": course_activities,
        }
        mongo_course_meta_data.insert_one(course_meta_data)
        return define_a_course(request)


def save_an_activity(request):
    if request.method == "POST":

        # Get the new activity from the form
        new_activity = request.POST.get("new_activity")
        has_groups = request.POST.get("has_groups")

        if has_groups == "on":
            has_groups = True
        else:
            has_groups = False

        # Create a python dictionary named course_data
        activity_data = {"activity_name": new_activity, "has_groups": has_groups}

        mongo_course_activity_collection.insert_one(activity_data)

        return render(request, "course_module/create_an_activity.html")
    else:
        # Handle other request methods (e.g., GET)
        print("Something not right")
        return render(request, "course_module/create_an_activity.html")

src/services/course_module/templates/course_module/create_an_activity.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
    />
    <title>Create an Activity</title>
  </head>
  <body>
    <div class="container">
      <h1>Create Activity</h1>
      <form action="{% url 'course_module:save_an_activity' %}" method="post">
        {% csrf_token %} {{ save_an_activity }}
        <div class="form-group">
          <label for="text-input">Activity Name</label>
          <input
            type="text"
            class="form-control"
            id="new_activity"
            name="new_activity"
            placeholder="Enter an Activity"
          />
        </div>
        <div class="form-group">
          <label for="checkbox"></label>
          <div class="form-check">
            <input
              class="form-check-input"
              type="checkbox"
              name="has_groups"
              id="has_groups"
            />
            <label class="form-check-label" for="radio-button1">
              Has Groups
            </label>
          </div>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
      </form>
    </div>
  </body>
</html>

src/services/course_module/templates/course_module/define_a_course.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
    />
    <title>Define a Course</title>
  </head>
  <body>
    <div class="container">
      <h1>Define a Course</h1>
      <form method="post" action="{% url 'course_module:save_course_meta_data' %}">
        {% csrf_token %}{{ save_course_meta_data }}
        <div class="form-group">
          <label for="courseActivities">Course Code</label>
          <input
            type="text"
            class="form-control"
            id="courseName"
            name="courseCode"
            placeholder="Enter course code"
          />
        {% for activity in course_activities %}
        <div class="form-check">
            <input type="checkbox" class="form-check-input" id="{{ activity.activity_name }}" name="activities" value="{{ activity.activity_name }}">
            <label class="form-check-label" for="{{ activity.activity_name }}">{{ activity.activity_name }}</label>
        </div>
        {% endfor %}

        <input type="submit" class="btn btn-primary" value="Submit">
      </form>
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  </body>
</html>

src/services/course_module/templates/course_module/define_course_activities_content.html
<!DOCTYPE html>
<html>
  <head>
    <title>Course Activities</title>
    {% load static %}
    <script src="{% static 'course_module/define_course_activities_content.js' %}"></script>
    <style>
      .form-group {
        margin-bottom: 15px;
      }

      .form-control-label {
        display: block;
        margin-bottom: 5px;
      }

      .form-control {
        width: 100%;
      }
    </style>
  </head>
  <link
    rel="stylesheet"
    href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
  />
  <body>
    {% csrf_token %}{{ save_course_activity_meta_data }}
    <div class="container">
      <div class="row">
        <div class="col-md-6 offset-md-3">
          <h1>Course Activities</h1>
          <form id="define_course_activities">
            <div class="form-group">
              <label for="course_code">Select Course:</label>
              <select id="course_code" name="course_code" class="form-control">
                <option value="" id="select-option">Select Course</option>
                {% for course in course_activities %}
                <option value="{{ course.course_code }}">
                  {{ course.course_code }}
                </option>
                {% endfor %}
              </select>
            </div>
          </form>
        </div>
      </div>
    </div>
  </body>
</html>